apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: b-ext-deploy
  labels:
    app: b-ext
spec:
  selector:
    matchLabels:
      app: b-ext
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: b-ext
        tier: frontend
    spec:
      containers:
      - image: wordpress
        name: b-ext-wp
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress.cfgr3xj38ihj.eu-central-1.rds.amazonaws.com:3306
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: b-ext-pass
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: b-ext-pass
              key: password
        ports:
        - containerPort: 80
          name: b-ext-cont
        volumeMounts:
        - name: b-ext-pv
          mountPath: /var/www/html
      volumes:
      - name: b-ext-pv
        persistentVolumeClaim:
          claimName: b-ext-pvc
